### ISSUE TITLE
Got troubles in configuring

### ISSUE THREAD

**Issue by SonicSkyJ12** [alefragnani/vscode-language-pascal#12]
Hey, i got some troubles in configuring the run build task in the tasks.json file, can you please give an example for it, or may be a tutorial video for it? Maybe you could also make the whole installation tutorial if you want to.
Also, i can't seem to configure debugging for it, any help please?
Thanks

**Comment by alefragnani** [comment]
Hi @SonicSkyJ12 , sorry for taking so long to answer you. 

About _debugging capabilities_, unfortunatelly there is no support. For now it is basically a _syntax highlight_ extension. I plan to add some other features, mostly to easier code navigation like _Go To Definition_ and _Peek Definition_ (besides _Go to Symbol_ that already exists), but debugging seems to be out of scope (at least today).

About _task build_, did you try the snippets provided in `README`? It shows you how to _build_ and how VS Code can _translate_ build erros and shows that in _Warnings_ window, for easier navigation. That snippet is based on calling `dcc32` Instead of `msbuild`, but still works. What is the problem are you having? Is not not building or the errors are not presented inside VS Code?

Hope this helps

**Comment by emiruyunka** [comment]
Concerning debugging, the Python extension for VS code (made by a third-party developer) does support debugging. I would really appreciate debugging capabilities for Pascal too ...

**Comment by alefragnani** [comment]
@emiruyunka I'm sorry to say, but debugging is out of scope. The Delphi debugger is not open, and I don't use FreePascal/Lazarus too much, to try out to integrate GDB. Maybe _when_ Delphi incorporate LLVM for Windows Desktop apps, we could take a look at LLDB.

I noted that there is already another extension for GDB in the Marketplace (https://marketplace.visualstudio.com/items?itemName=webfreak.debug). Maybe you could try out.
