### ISSUE TITLE
[BUG] - Continual WARNING popup for files out of source tree

### ISSUE THREAD

**Issue by Quietus** [alefragnani/vscode-language-pascal#125]
**Environment/version**
- Extension version: 9.5.1
- VSCode version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
- OS version: Linux x64 5.10.0-18-amd64 ( Debian GNU/Linux 11 (bullseye) )

**Steps to reproduce**

1. Use the pascal extension
2. Create a project using git
3. Create a new file, or edit an existing file while having your .vscode folder outside the source tree.

**Result**
For editing a file: a popup stating "Some error occured: Warning: '<folder>/.vscode/GTEMP.pas' is out of source tree. ignored." with a Source of Pascal (Extension).
For creating a new file: a popup stating "Some error occured: Warning: '<folder>/path/to/newfile.pas' is out of source tree. ignored." with a Source of Pascal (Extension).

I accept the extension needs me to add the files to the source tree - but the popup is unnecessary, a line in problems would do (and be less intrusive).  This also seems new - I've been using your extension for a while and I don't remember this happening before the latest vscode updates.

**Comment by alefragnani** [comment]
Hi @Quietus ,

What do you mean about _`.vscode` folder outside the source tree_? Is it in the root folder of your project?

I mean, the `.vscode` folder is created and managed by VS Code, and is located in the project root. The Pascal extension _uses_ this folder to store the `GTEMP.pas` _temporary file_, and this file is used by `gtags` and `global` to parse/generate the tags and provide you code navigation.

By the way, the message you see is generated by `global`, as `global` requires the source being analyzing to be within the project.

About the popup itself, I consider this message to be too important to be in the `Problems` panel, since it mean the extension itself is not working properly. A message in `Problems` should be for something that you could _ignore_. Anyway, feel free to open a separate Feature Request for this change, which could leave to the user decide which UI to be used to present such messages. 

Hope this helps.
