### ISSUE TITLE
 Add Linux support to the FreePascal task snippet

### ISSUE THREAD

**Issue by nilya** [alefragnani/vscode-language-pascal#15]
Please add this code to tasks.json snippet for FreePascal so it can be used in Linux:
```diff
 		"windows": {
 			"command": "FPC.EXE_PATH"
 		},
+		"linux": {
+			"command": "fpc"
+		},
```

And maybe change `"args": ["YOUR_FREEPASCAL_PROJECT"]` to the `"args": ["${relativeFile}"]` so the task will compile the current opened file?

**Comment by alefragnani** [comment]
Hi @nilya ,

Since these are just examples, it's better to have a _dynamic value_ in it, and explain its meaning right above (just like the Windows piece). So, it should be `"command": "FPC_BIN_PATH"`, explaining the meaning of "FPC_BIN_PATH".

About the `YOUR_FREEPASCAL_PROJECT` value, I prefere maintain as is, updating its meaning to also refer to the `file`, not just the `project`.

Based on the two issues that you reported, I guess you are using `Copy and Paste` from the `README.md` file, each time you need it. It's better to you to create snippets for the `JSON` languages, based on these examples, so when you create new task builds, you already have a _Build FreePascal_ task. A snippet to create snippets :)

Hope this helps
