### ISSUE TITLE
[FEATURE] - Disable "What's New" advertisements

### ISSUE THREAD

**Issue by domenic** [alefragnani/vscode-language-pascal#150]
I'd like to never see the "What's New in Pascal" page again. When I'm launching a new VSCode window, it's to get work done, not to learn about an extension that I use maybe one in a hundred editing sessions.

I'd like to keep the Pascal extension installed, but never have to worry about it.

Right now it seems the only way to avoid this is to disable the Pascal extension and re-enable it for those rare editing sessions where I'm working with Pascal code.

Note that VSCode itself has a setting to disable its own "What's New" advertisements. So I'm asking for this extension to do a similar thing.

**Comment by alefragnani** [comment]
Hi @domenic ,

The What’s New page is shown only when new versions, containing new features, are released. Versions with fixes only, are silent. The latest version was an exception because it contained no feature, but only the publishing to open-vsx.org.

But, if you don’t use the extension that much, there are a few ways to avoid the What’s New page:

1. Keep the extension disabled, and enable it only when really necessary
2. Use the **Profiles** feature and install the extension exclusively on that profile, so it won’t be available (and updated) on your regular day to day usage
3. Use the `Install Another Version…` option, so VS Code won’t update the extension anymore

Based on your comments, I understand the best fit is option 3, because it will be there, available and unchanged.

If these options doesn’t answer your requirements, there are a few other extensions available in the marketplace that provides similar features, like OmniPascal, DelphiLSP, among others.

Hope this helps
