### ISSUE TITLE
No symbols found

### ISSUE THREAD

**Issue by bartosz-antosik** [alefragnani/vscode-language-pascal#34]
Hi! I have an issue with symbols navigation and I am not sure whether this is configuration or something with the extension: I have configured global (with ctags, pygments etc.) and it seems to be working correctly. I can see the symbols table is building correctly (e.g. with `gtags -v --explain`) and dump symbols (e.g. with `gtags -d GRTAGS`) but they do not appear in any of VSCodes lists: that is when I press `Ctrl+T` (#) or `Ctrl+P` (@) etc.

Am I doing something wrong? Is there anything else I can test to determine whether something is wrong with my configuration or is it something with the extension?

**Comment by alefragnani** [comment]
Hi @bartosz-antosik ,

If you are able to run `gtags` and `global` via command line, but it does not work via VS Code, maybe could be an issue with `PATH`. Could you do this two checks:

1. Open a Terminal session inside VS Code and run `gtags` and `global` commands. You have to do this to be sure that VS Code recognizes the `PATH` environment variables. 
1. Run the `global` command inside that Terminal session. To check for symbols from a file, the command is: `global -f relative_path_to_file`, like `global -f src\uMyUnitFile.pas`
1. If both commands works, then try to look for some error message in `Toggle Developer Tools / Console`

BTW, which OS are you using?

Hope this helps

**Comment by bartosz-antosik** [comment]
I am sorry, it appears that it is not a problem with the extension! Your message directed me to testing whether the gtags/global work and it seems there is some problem. Looks like gtags does extract the tags but global does not show anything related to particular files. Seems like the reason is related to the fact that my files have `.pp` extension.

**Comment by alefragnani** [comment]
That's right. It seems to be a limitation in `ctags`. I tried to modify `gtags.conf` and `ctagsXX\pascal.c` to _recognize_  `.pp` files, with no success. Maybe `ctags` needs to be rebuilt to that.

Let me know if you find out how to make it work...

**Comment by alefragnani** [comment]
That's great it worked! 

Yes, I turned back because _I couldn't believe_ that it would require rebuild `ctags` just to recognize new file extensions 😄 . 

The `ctags`/`global` tooling is a _"tagging system"_ so it just recognizes _tags_. It does not understand/differenciate between declaration and implementation sections. To do that, a `AST Parser` is needed. That's why `Go to Definition` just _"kinda works"_ 😁 . 

The `Show all Symbols` command is not available because `gtags`/`global` does not support. You can only look for symbols in one file at a time (or a single folder), but not the entire workspace. 

To have a better experience, I must replace `gtags`/`global`, and build a new tooling, which could also give you #33 . What do you think about it?
