### ISSUE TITLE
Unable to compile project

### ISSUE THREAD

**Issue by denis-budyak-aurea** [alefragnani/vscode-language-pascal#39]
Hi! I forked you project to make a support for «Component Pascal» aka «BlackBoxComponentBuilder». 
Actually I have a syntax highlight working already, but due to its dynamic nature blackbox allows to do interesting things like dynamic completion from RTTI and so on. This is in a far future... 
Meanwhile It looks like you forgot to add some files to git, like src/whats-new/* and vscode-whats-new/*

Now trying to disable all references to missing files...

**Comment by alefragnani** [comment]
Hi @denis-budyak-aurea ,

First of all, sorry for taking so long to answer you, but I was in enjoying the New Year's holiday 😁 .

I'm glad to know you are using my extension as the basis to yours. I did it myself when I started creating extensions, combined with the [Yeoman Generator](https://www.npmjs.com/package/generator-code) which the VS Code team provides. It has improved a lot since the early days, and it uses _up to date_ templates, so you could give it a try too.

About the error you reported, there is no missing file. These files are in a `git submodule`, which I created because all of my extensions should share the same resources. Since you are forking my project but will not send merge requests (because you are creating a separate project), you did the right thing. Just remove the references, because you will not use it.

Hope this helps.
