### ISSUE TITLE
Problems with autocompletion

### ISSUE THREAD

**Issue by AnsonYeung** [alefragnani/vscode-language-pascal#41]
Some of the auto complete does not work well.

Example:
When I type
 if ... then 
Then I pressed enter, the enter key will be eaten.
What I want is skip to the next line with indent.
This only happens when I pressed the enter key second time.

Besides, the snippet of begin...end is bad.
It inserts two position, one between begin end and one after the end keyword.
However, when I type code between begin end, the auto complete function will not work at all. There will be no hint at all.

Also, can you make a option to capitalize the first letter of keywords?
For example, when I type "if" then pressed space, the "if" keyword will become "If"

Lastly, it will be good if the main begin end will be automatically insert the dot instead of a semicolon.

**Comment by AnsonYeung** [comment]
Some of the snippet have the same name with the keyword, this requires manually choose between keyword and snippet, which is inconvenient

**Comment by alefragnani** [comment]
Hi @AnsonYeung ,

I think you are confusing _auto complete_ and _snippets_. 

The _auto complete_ feature, which is a VS Code functionality, is responsible for what you see in your first (**typing if .. then**) and second (**missed auto complete while using snippets**), so, you should report this directly in VS Code repository.

About the two positions in `begin ... end` snippets, yes, it could be improved. I'll remove the second position, thanks 👍 

About capitalizing the first letter of keywords, I'm sorry, but there is no way (API) to create such customization. I think you should look for another extension that does things like that (use a user created dictionary to auto replace specific keywords). 

About replacing the **begin...end** end snippet to use dot instead of semicolon, I won't change that, because the semicolon is a lot more used than dot. But I invite you to make a pull request, adding a new snippet with that new snippet.

Finally, about the snippets with the same name as a keyword, I think you are talking about `begin`, `for`, and others, right? Well, some of the snippets where created to replicate what you see in Delphi, and Delphi itself has exactly the same _inconveniences_. Sorry, but I prefer having the same snippets on both tools (which I use everyday) instead of two different _keybindings_ for each tool.

Hope this helps.

**Comment by AnsonYeung** [comment]
@alefragnani I experience a big problem when typing while...do loop. When I type do, it will turn to `destructor Destroy; override;` sometimes. It is very annoying, can you remove it?

**Comment by alefragnani** [comment]
Hi @AnsonYeung ,

This is also caused by VS Code _auto complete_ feature, not the snippet itself.

I think you should take a look at `editor.wordBasedSuggestions`, `editor.quickSuggestions`, `editor.suggest.snippetsPreventQuickSuggestions` and other related settings. Maybe turning off suggestions and/or snippets, would fit your needs to avoid VS Code messing around while you type.
