### ISSUE TITLE
read iss files?

### ISSUE THREAD

**Issue by goldbergjeffrey** [alefragnani/vscode-language-pascal#7]
Hi,

I'm using inno setup and I'd love to edit the files in code with fun colors.  How do I get your pascal tool to recognize iss files?

**Comment by alefragnani** [comment]
Hi @goldbergjeffrey ,

Inno Setup uses a _INI like_ syntax, with a _Pascal scripting_ section. So, you have in fact two distinct languages, and until now, VSCode does not support two languages for the same file.

But, if you don't worry about losing the INI syntax capability, you could use `"files.associations"` _User Setting_ and associate `.iss` files with the `Pascal` language. So, when you open a Inno Setup file, it will be highlighted as Pascal.

Otherwise, a new language support must be created, that should handle INI and Pascal syntax at the same time.

Hope this helps.
